version: '3.8'

services:
  nest:
    container_name: nest
    image: skazuki/alpine-node-yarn-install
    restart: always
    volumes:
      - .:/node
    networks:
      - rate-checker

networks:
  rate-checker:
    external: true
